### PR TITLE
Fix: Show message when user have no report for selected days

### LINKED ISSUE #311: Improve user feedback for GitHub API errors and edge cases
### Description
While using Scrum Helper, GitHub API failures can currently result in little or no visible feedback to the user. This may be confusing in cases where data is not generated as expected.

### Problem
Some common GitHub API scenarios are not clearly surfaced in the UI, such as:
- Invalid or non-existent GitHub usernames
- Missing or expired GitHub personal access tokens
- GitHub API rate-limit responses (e.g. HTTP 403)
- Empty activity results caused by API errors rather than no contributions

### Proposed Improvement
- Detect common GitHub API error responses
- Display clear, user-friendly messages in the popup UI
- Add a fallback UI state instead of blank or unclear output
- Keep changes small and incremental, focusing only on feedback and messaging

### Benefits
- Improves usability and reduces user confusion
- Makes error states easier to understand and debug
- Enhances overall reliability and user trust in the extension

I would be happy to work on this issue and submit a pull request if this approach aligns with the project’s direction.  
Please let me know if you have any preferences or suggestions before I begin.

### PR DESCRIPTION
**Pull request by Mateeb-Haider**
### 📌 Fixes

Fixes #311 

---

### 📝 Summary of Changes

- Added a fallback message in the report output when there is no activity in the selected day/range.
- Prevented empty report sections by showing a meaningful contribution status instead of an empty list.
- Kept behavior consistent across popup and email report generation paths.

---

### 📸 Screenshots / Demo (if UI-related)
Before
image

After
image

---

### ✅ Checklist

- [x] I’ve tested my changes locally
- [x] My code follows the project’s code style guidelines

---

### 👀 Reviewer Notes

Please verify:
- No-activity days now render a meaningful message instead of an empty report section.
- Existing report output remains unchanged when activity exists.

## Summary by Sourcery

Show a meaningful fallback message in scrum reports when no activity exists for the selected period and reuse this behavior across email and popup outputs.

Bug Fixes:
- Display a clear no-contributions message instead of empty report sections when there is no activity in the selected date range.

Enhancements:
- Introduce a shared helper to build the activity list HTML so email and popup reports use the same no-activity behavior.

### CODE REVIEW

**Comment by Mateeb-Haider** [comment]
@vedansh-5, @hpdang, @mariobehling 
Please review this PR at priority. It fixes empty daily reports by showing a clear “No contributions found for this period” message, which is important for user consistency and avoids confusing blank output. A quick review and merge would help improve reliability for all users.

**Review by Saksham-Sirohi — CHANGES_REQUESTED** [review]
It would be appreciated if this message did not appear as a list entry

**Comment by Mateeb-Haider** [comment]
> It would be appreciated if this message did not appear as a list entry

image

@Saksham-Sirohi 
I implement the change please take a look. Thanku!

File: src/scripts/scrumHelper.js [hunk 1]
```diff
@@ -1041,16 +1038,25 @@ function allIncluded(outputTarget = 'email') {
 		return date.toLocaleDateString('en-US', options);
 	}
 
+	function buildActivityListHtml() {
+		if (lastWeekArray.length === 0 && reviewedPrsArray.length === 0) {
+			return '<div style="padding: 0 12px;">No activity to report for this update.</div>';
```
Comment (vedansh-5) [inline src/scripts/scrumHelper.js]: Please update this to no activity to report for the selected time period.

**Review by vedansh-5 — COMMENTED** [review]
Thanks @Mateeb-Haider for your contribution.

File: src/scripts/scrumHelper.js (hunk 1 above)
Comment (Mateeb-Haider) [reply src/scripts/scrumHelper.js]: > Please update this to no activity to report for the selected time period.

 I apply the required change now PR is ready to merge
thanku!

**Comment by Mateeb-Haider** [comment]
image
image

@vedansh-5 I implemented all required changes by you and copilot as well and the output attached after the change please take a look when you have free time
Thanku!

**Review by vedansh-5 — COMMENTED** [review]
Thanks @Mateeb-Haider for your contribution.

Please pull the latest changes from the base branch and rebase your PR. Also resolve the existing merge conflicts.
Other than that, this PR looks good to me.

**Comment by Mateeb-Haider** [comment]
@vedansh-5
PTAL!

**Review by vedansh-5 — APPROVED** [review]
Thanks @Mateeb-Haider LGTM!
